### PR TITLE
[#269] Removed unecessary absolute positions,  aligned and resized el…

### PR DESCRIPTION
**Pull request by Omoorion**
…ements

### CODE REVIEW

**Comment by Ido-Barnea** [comment]
@Omoorion Looks like you have merge conflicts 😆

**Comment by Ido-Barnea** [comment]
@Omoorion Did you bother testing your changes?
image

**Comment by Monkey-bored** [comment]
> @Omoorion Looks like you have merge conflicts 😆 

RIP 🫡

**Comment by Omoorion** [comment]
I fixed them 😈

**Comment by Omoorion** [comment]
> @Omoorion Did you bother testing your changes? image

What does brother mean

**Comment by Ido-Barnea** [comment]
> > @Omoorion Did you bother testing your changes? image
> 
> What does brother mean

It looks completely different from the current UI and for the worse

**Comment by Omoorion** [comment]
Personally I think it looks better, what's bad about it?

**Comment by Omoorion** [comment]
How does this mess look better to you 
image

**Comment by Ido-Barnea** [comment]
> How does this mess look better to you image

The only problem I see is the missing margin on the top-left side. Please use `master` branch as a reference.

**Comment by Ido-Barnea** [comment]
@Omoorion same margin problem with the top side of the logs container

**Comment by Ido-Barnea** [comment]
Closing due to inactivity @Omoorion.
Should you wish to revisit this in the future, please feel free to reopen or submit a new PR.

**Pull request closed without merging**
